### ISSUE TITLE
Minion and support gem

### ISSUE THREAD

**Issue by poupet** [Mattc33/Necronomicon#3]
Hello,
I start reading a bit your explanation about pet and find something confusing here :
https://github.com/Mattc33/Necronomicon/blob/master/Necronomicon.md#minions-and-support-gem-swapping

You said that Pet supported gem are snashooted but them you said that they can be changed.

Maybe you should re-write this part by only saying that Support gem are calculated "on the fly" : if you change a support gem, it is changed on the pet already summon too.
The part about removing a gem to reduce mana cost then put it in back is a really good example.
But the chest swap doesn't work anymore (I think so as snapshot is no more).

I will continue my readying and make issue if something else is no more accurate.

**Comment by Mattc33** [comment]
Your right it is confusing. Thank you for pointing this out. I don't think that section is applicable anymore.
